#!/usr/bin/env python
"""
CLI utility for logging the time you spend on things.
    Usage: `logtime --help`
"""

from datetime import date, timedelta
import click
import logtime_cli.logfile_io as logfile_io


@click.group()
def entry_point():
    """logtime"""
    pass


if __name__ == '__main__':
    entry_point() #pylint: disable=no-value-for-parameter
