#!/usr/bin/env python

import click
from datetime import date, timedelta
from logtime_cli.logtime import LogTime, OpenLogfileForDate


def _openPrevious(ctx, param, value):
    if not value:
        return
    previousDate = (date.today() - timedelta(days=value))
    OpenLogfileForDate(previousDate)
    ctx.exit()


@click.command(context_settings=dict(help_option_names=['-h', '--help']))
@click.option('--previous', '-p', type=int, callback=_openPrevious, expose_value=False, is_eager=True, help='Open a logfile X days in the past and exit.')
@click.argument('entry', nargs=-1)
def cli(entry):
    """Log what you just finished doing.

    Examples:

    \b
    lt python docs
    lt john: discuss python docs
    """
    if not entry:
        OpenLogfileForDate(date.today())
    else:
        LogTime(' '.join(entry))

if __name__ == '__main__':
    cli()
