#!/usr/bin/env python

import click
from logtime_cli.logtime import LogTime, OpenLogfileToday

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])


@click.command(context_settings=CONTEXT_SETTINGS)
@click.argument('entry', nargs=-1)
def cli(entry):
    """Log what you just finished doing.

    Examples:

    \b
    lt python docs
    lt john: discuss python docs
    """
    if not entry:
        OpenLogfileToday()
    else:
        LogTime(' '.join(entry))

if __name__ == '__main__':
    cli()
