#!/usr/bin/env python

import click
from datetime import date
from logtime_cli.logtime import LogTime, OpenLogfileForDate


@click.command(context_settings=dict(help_option_names=['-h', '--help']))
@click.argument('entry', nargs=-1)
def cli(entry):
    """Log what you just finished doing.

    Examples:

    \b
    lt python docs
    lt john: discuss python docs
    """
    if not entry:
        OpenLogfileForDate(date.today())
    else:
        LogTime(' '.join(entry))

if __name__ == '__main__':
    cli()
